### ISSUE TITLE
Spacing Bug in Branch paren

### ISSUE THREAD

**Issue by xythyl** [xythyl/rshell#7]
My attempt to fix issues caused when there are no spaces around connectors has surfaced a small hard to detect bug. The bug must be coming from adding spaces before and after connectors. There should be no exec error.

`echo&&echo||echo` returns this
` `
`exec error: No such file or directory`
` `
while `ls&&ls||ls` returns this
`bin  LICENSE  Makefile	README.md  src	tests`
`bin  LICENSE  Makefile	README.md  src	tests`

**Comment by jgome043** [comment]
fixed by rearranging checks for connectors to *just* before their respective while loops.
